### ISSUE TITLE
Right now is not in the Obsidian's Community plugins 

### ISSUE THREAD

**Issue by David7ce** [StrangeGirlMurph/obsidian-wikipedia-search#1]
It can be installed downloading [main.js](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/releases/download/1.0.0/main.js), [manifest.json](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/releases/download/1.0.0/manifest.json) and put the files into the plugins folder of your Vault (/path-vault/.obsidian/plugins)

Just to mention for the README instructions.

**Comment by StrangeGirlMurph** [comment]
Added the manual installation in my last commit :)
