### ISSUE TITLE
[FEATURE] Multiple formats

### ISSUE THREAD

**Issue by kerbless** [StrangeGirlMurph/obsidian-wikipedia-search#10]
# Description of the Problem

I use Wikipedia articles mainly in two ways:
- to have a link to the article
```
[{title}]({url})
```
- to have the extract introduce a note
```
> [!quote] {title}
> {extract} - [Wikipedia]({url})
```

# Description of the Solution

So I'd like to have a "format" for both. For example different hotkeys for different formats or, after selecting an article, choosing with which format to use.

# Additional

The workaround for this right now is to use the second "quote" format and remove the extract when I only need the link, which is really annoying, or use the first "link" format and add the extract manually, which is also annoying.
Another alternative is using [this other plugin](https://github.com/jmilldotdev/obsidian-wikipedia/releases) for the extracts and this plugin for the links, the other plugin however does not not work well when using multiple languages.

The second format breaks when the Wikipedia articles has line breaks (no pun intended), which is annoying and does not happen in the other plugin linked here above.

**Comment by StrangeGirlMurph** [comment]
Thank you for the feature request! I'll think about a good way to add this!

> The second format breaks when the Wikipedia articles has line breaks (no pun intended), which is annoying and does not happen in the other plugin linked here above.

Hmm can you give an example? The article of [Albert Einstein](https://en.wikipedia.org/wiki/Albert_Einstein) Has line breaks in the abstract and the output with your format string works fine for me:
![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/62220780/010a8436-c0b5-4097-acd0-56148d8eb35b)

**Comment by StrangeGirlMurph** [comment]
I added the feature and it's already in the newest release :)
Please comment again about the "bug" you mentioned and I asked about in the previous message!

**Comment by kerbless** [comment]
Hey that was fast, thanks a lot for your work it's exactly what I needed!

Only one thing, I believe that the {{extract}} template doesn't respect the "en:" prefix, at least when used as an additional template.

If I use:
![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/32358946/827f00a8-96b8-4afa-a599-ee4b490644dd)

and select my additional template:
![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/32358946/58c50ae3-8be8-485d-9d43-fd3830d619c2)

I get the extracted article in Italian (you can also see the problem with the quote block here) and the link to Wikipedia in english:
![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/32358946/87a2721c-3487-49f6-a43a-7b340ab2fc79)
![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/32358946/86595dcc-3a43-48e5-9955-4d82ae0a86e1)

My settings:
![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/32358946/51f738ef-d472-4a9d-ae2d-dec8f7ec4301)

The article on Wikipedia:
![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/32358946/c4a9ecad-e425-48df-a5a9-b58d00e97564)

One thing you could try (which would be good to me) is cutting the extract to the first newline and adding "..." or just substituting new lines with spaces? The language problem is more like a bug so I hope it's easy to fix c:

**Comment by StrangeGirlMurph** [comment]
@kerbless Oh yeah that extract language thing is a bug! The new release with the patch is already out and ready to be updated :) Thanks for telling me about it. Good to hear you're happy with the feature :)

> you can also see the problem with the quote block here

I don't know what you mean.

> One thing you could try (which would be good to me) is cutting the extract to the first newline and adding "..." or just substituting new lines with spaces?

I'll think about adding this with my next major release. I am currently working on opening Wikipedia articles right in obsidian in a new tab :)
