### ISSUE TITLE
[BUG] doesnt support hebrew search

### ISSUE THREAD

**Issue by YMHJERUSALEM** [StrangeGirlMurph/obsidian-wikipedia-search#12]
# Description

when i write a search in hebrew it doesn't support it. there are many articles in Wikipedia I know, but the search doesn't get them

# To Reproduce

# Expected Behavior

# Additional Info

**Comment by StrangeGirlMurph** [comment]
Hey! Thanks for your bug repot.
Can you be a bit more specific?
Everything seems to works for me.

![grafik](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/62220780/c20a7f48-586f-43f2-824d-1075a2ee785a)

**Comment by StrangeGirlMurph** [comment]
I'll close this due to inactivity and me not being able to reproduce this bug. Please just comment again if this bug is still there.

**Comment by YMHJERUSALEM** [comment]
thanks a lot man!
i didnt know about the need to put the "he:" before serching' it solves it all
i recomend adding this advice in the manual

thanks!

(sorry for the late respond, i missed the notification)

**Comment by StrangeGirlMurph** [comment]
Well I mentioned it in the readme. Maybe I can elaborate a bit more though.

You're welcome :)
