### ISSUE TITLE
[FEATURE] Add image

### ISSUE THREAD

**Issue by rensftw** [StrangeGirlMurph/obsidian-wikipedia-search#16]
# Description of the Problem
It would be awesome if we can optionally add the "main" Wiki article image in a template.
Example of a Wiki article with a "main" image: https://en.wikipedia.org/wiki/Protozoa

# Description of the Solution
For example:
```markdown
> [{title}]({url})
> {image}
> {intro}
```

and then `{image}` is resolved to `![article image](https://en.wikipedia.org/wiki/File:<IMAGE FROM ARTICLE YOU SEARCHED>.jpg)`

# Additional

# Considered Alternatives
The image could be part of `{intro}` itself; but I consider this a worse solution because it's less granular.

PS: Thank you for the great plugin, documentation, and care for this repo! 🙏

**Comment by StrangeGirlMurph** [comment]
Uh yeah that sounds awesome! Thank you so much for the request. I love the idea. I'll see what I can do about it once I am back home on Sunday :)

**Comment by StrangeGirlMurph** [comment]
Done! The core functionality is there :)

**Comment by rensftw** [comment]
Thank you @StrangeGirlMurph 🙌 
I tried it out, works like a charm

**Comment by StrangeGirlMurph** [comment]
You're welcome. That's wonderful :)
Btw keep in mind that most articles just don't have a thumbnail.
