### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by ppmw99** [StrangeGirlMurph/obsidian-wikipedia-search#2]
downloaded zip from here.  extracted ALL to a temp directory.  copied all to directory C:\myvault\.obsidian\plugins\wikipedia-search
restarted obsidian
could see Wikipedia Search at bottom of list of community plugins.  Tried to togge it on but it says "Failed to load plugin wikipedia-search"
![Screenshot 2023-03-21 150135](https://user-images.githubusercontent.com/16546991/226648018-26e97fbe-014e-4dc7-b9ea-5fd8fa0f2cce.png)
I cannot see a main.js file  in the list in the zip 
What do I need to do to enable the plugin ?

**Comment by StrangeGirlMurph** [comment]
You're welcome :) Lets hope this plugin soon gets accepted to the plugin list!
Updating is pretty tedious rn... But I think you might like the new release!
