### ISSUE TITLE
[BUG] {thumbnail} Templates Not Working on Mobile

### ISSUE THREAD

**Issue by azuryst** [StrangeGirlMurph/obsidian-wikipedia-search#20]
# Description

Hi, is there anything preventing image insertion on mobile? `{thumbnail}` templates works fine on desktop for the same Wiki article, but don't work on mobile for me. Thanks! Great plugin!

# To Reproduce

These work on desktop, but not on mobile, for the same article that has an image:

```
[{title} - Wiki]({url})
{thumbnail}
_{description}_
{intro}

[{title} - Wiki]({url})
{thumbnail}
_{description}_
```

This template works on desktop and mobile, which simply has the {thumbnail} placeholder omitted:

```
[{title} - Wiki]({url})
_{description}_
```

# Expected Behavior

Expecting insertion to be added to the note on mobile, but nothing happens, no error message or anything, and cursor just blinks in place.

# Platform

Obsidian macOS 1.4.16
iOS 17.1.1

**Comment by StrangeGirlMurph** [comment]
Hey @azuryst! Thanks for your bug report. Sadly I couldn't reproduce this. It seems to work great on my android phone. I also couldn't find any obvious signs in the code that would lead to this behavior :( That means we have to dig deeper... Maybe I can reproduce it with the exact article you wanted to link. Maybe something about that breaks it. Your wikipedia search settings would probably be usefull aswell. Please send those along. ~ Murphy

**Comment by azuryst** [comment]
Hi @StrangeGirlMurph! Thank you for your reply. Interesting that it is working on your android. I just tested on my iPad too, same issue. This seems to be an iOS issue as far as I can tell-- I've tried to isolate things in order to rule out anything else causing it:

- created a fresh new Obsidian Vault, only added your plugin. _--issue persists_
- tried adding Thumbnail width setting in plugin settings to both 200 and 300, as well as leaving blank. _--that didn't affect it._
- tried creating a template with just `{thumbnail}`. _--template works on desktop, not on mobile._
- tried with multiple articles that are known to have a main image (e.g. Obsidian, Apple Inc. etc) _--issue doesn't seem to be specific article related._
- tried turning on all of of your `Workflow optimizations`, to see if any had an effect. _--didn't make any difference._

Since I created a new default Vault and am still experiencing the issue, it doesn't look like there are any conflicts with other plugins. I also thought it might be an iOS security setting for clipboard (maybe??). I checked in iOS settings for Obsidian, and `Paste from Other Apps` is set to `Allow`, so that shouldn't be an issue either.

I included screenshots of the mobile settings I tried, as well as a test from the Obsidian macOS app, to show that the articles are inserting images correctly there. For mobile, there's nothing really to show; the command palette just returns to the note with the blinking cursor in place.

Thanks! Hope this helps. This is a handy little plugin, I really hope to get it working on mobile too.

<a href="https://imgur.com/y7R1OYU"><img src="https://i.imgur.com/y7R1OYU.jpg" title="Wikipedia Search plugin settings _mobile" width="300"/></a>
<a href="https://imgur.com/2QP6lVI"><img src="https://i.imgur.com/2QP6lVI.jpg" title="Wikipedia Search plugin settings _mobile 2" width="300"/></a>
<a href="https://imgur.com/0e9xNPj"><img src="https://i.imgur.com/0e9xNPj.jpg" title="Wikipedia Search test _desktop (works fine)" width="300"/></a>

**Comment by StrangeGirlMurph** [comment]
Thank you so much for your help. I actually managed to reproduce this now on my iPad and I am already on it. I am sure we get it to work :)

**Comment by StrangeGirlMurph** [comment]
I fixed it with the newest release :) See: https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/releases/tag/2.2.1
Thank you so much for creating an issue! It was an easy fix but a big error. I probably wouldn't have noticed it myself. I don't use the plugin on my ipad ^^

**Comment by azuryst** [comment]
> I fixed it with the newest release :) See: https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/releases/tag/2.2.1
> 
> Thank you so much for creating an issue! It was an easy fix but a big error. I probably wouldn't have noticed it myself. I don't use the plugin on my ipad ^^

Woohoo!! thank you so much!!
