### ISSUE TITLE
[BUG] Linking article which is a redirect fails to fetch the introduction

### ISSUE THREAD

**Issue by redactedscribe** [StrangeGirlMurph/obsidian-wikipedia-search#21]
# Description

I use `{description}` in my template and if I try to link an article which does not have one, the insertion of the template fails.

# To Reproduce

- Link an article which has no description with `{description}` in your template.

# Expected Behavior

The expectation is that _something_ would be inserted because the article itself exists, just skip over inserting the description and pop up an error saying that no description was inserted because one didn't exist for the article.

Thanks.

**Comment by StrangeGirlMurph** [comment]
For me it works just as expected. It just ignores the `{description}` when there is no description and tells you about it. This must be some different bug or something specific about the article you were trying to link. Please tell me what article caused this and check the console for any errors (use `CTRL+SHIFT+I` and then go to the console tab).

**Comment by redactedscribe** [comment]
On second look, it also says it couldn't fetch the introduction:

![Obsidian_2023-11-18_17-31-44](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/25013746/ad2efd38-29fe-4a25-94f7-42b436ab4363)

It's actually nothing to do with the description in fact. The introduction on the article for [File Type](https://en.wikipedia.org/wiki/File_type) is the issue, and if I had to guess, it's because it's [a redirect to another article (File format)](https://en.wikipedia.org/w/index.php?title=File_type&redirect=no).

**Comment by StrangeGirlMurph** [comment]
I fixed it! It was actually a pretty big bug. Sorry I haven't noticed it myself. Thank you so much for creating this issue!

**Comment by redactedscribe** [comment]
Thanks @StrangeGirlMurph!
