### ISSUE TITLE
[FEATURE] Support Templater templates for note creation

### ISSUE THREAD

**Issue by StrangeGirlMurph** [StrangeGirlMurph/obsidian-wikipedia-search#22]
# Description of the Problem

Limited options for note creation templates.

# Description of the Solution

Supporting Templater templates would open  huge amounts of possibilities. 

--- 

@ValiHar please elaborate on what exactly you had in mind :)

**Comment by ValiHar** [comment]
Sure, let's go: 
Currently, Wikipedia Search enables you to query for a Wikipedia article and then save the Title and Intro Section as a new Markdown file via a templating syntax defined in the plugin itself. It would be helpful however to provide a template file in [Templater](https://github.com/SilentVoid13/Templater) syntax that allows you to further customize your Wikipedia imports. 

This enables the following: 
- Use custom properties in all files imported from Wikipedia, e.g. tags
- Define a custom structure for the imported files
- Use custom javascript to transform imported articles
- A deeper integration with the obsidian ecosystem 😄

**Comment by ValiHar** [comment]
@muckmuck96 if you have a moment of your time to spare, we can look into this together in a free moment at work in the next week!

**Comment by StrangeGirlMurph** [comment]
I need it even more specific ^^

Do you want to use Templater syntax in the Wikipedia Search template string or make the Wikipedia Search syntax and values available in existing Templater templates?
What exact workflow did you have in mind?

**Comment by ValiHar** [comment]
Hehe okay :) 
So I have a large folder with many templates, for my daily notes, my library imports via the awesome [Zotero Integration ](https://github.com/mgmeyers/obsidian-zotero-integration)plugin, and many more things. 

<img width="355" alt="Screenshot 2023-11-27 at 12 08 45" src="https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/28244552/35977cd0-d984-4e14-a70f-850af55fbad7">

All these files include some custom template strings of individual plugins and are enhanced with template syntax. Basically what I want is for this template file to be used to instantiate the newly created Wikipedia file. If that's possible, I'm able to customize the Wikipedia file beforehand and add tags and many more properties. 

Here's an example of how such a template could look like: 
<img width="691" alt="Screenshot 2023-11-27 at 12 22 43" src="https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/28244552/9a881912-9df2-4b67-ae0c-9add6cb3f0f3">

**Comment by ValiHar** [comment]
---
tags:
  - Knowledgebase
  - Wikipedia
  - ComputerScience
created: <% tp.file.creation_date() %>
author: Valentin Hartig
---

# [{{Wikipedia Title}}]()
{{Wikipedia Intro}}


```dateview
TABLE file.cday AS "Created on", file.tags AS Tags FROM #Wikipedia WHERE contains(file.path, "KnowledgeBase") & contains(file.tags, "#ComputerScience")
```

---
Sources: [Wikipedia]({{Wkipedia Link}})

**Comment by StrangeGirlMurph** [comment]
Oh wow okay this is actually super easy. I checked the Templater settings and found this:

![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/62220780/42e1c765-2a47-4467-a73a-a818f42eac15)

Which means that Tempalter syntax is already supported and works! Tried it out! I just have to add support template strings in file format to make it easier to work with them. I can add that in the next few days :)

**Comment by StrangeGirlMurph** [comment]
Done :) Check out the new version and the updated docs!

**Comment by ValiHar** [comment]
Hi @StrangeGirlMurph, 
thanks for implementing this so fast :) Do I understand it right that the template window now supports template syntax but the plugin doesn't support providing the template via a file? 😄

**Comment by ValiHar** [comment]
Nvm, I found the toggle for the file path!

**Comment by StrangeGirlMurph** [comment]
The docs should be helpful with questions like this as well :) (And if you ever feel like they don't explain something well enough create an issue for it!)
