### ISSUE TITLE
[BUG] Linking of articles not available

### ISSUE THREAD

**Issue by ValiHar** [StrangeGirlMurph/obsidian-wikipedia-search#23]
# Description

When trying to link articles with the commands described in the documentation, the corresponding command "Wikipedia Search: link article" is not available.  

# To Reproduce

Open Obsidian Command Pallet and search for Wikipedia Search. 

# Expected Behavior

The command for linking articles to create a new Markdown file appears. 

# Additional Info
## Screenshots
<img width="681" alt="Screenshot 2023-11-27 at 11 28 15" src="https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/28244552/f921c30a-474e-495e-98ba-b1d849dfe8f7">

## Platform
OS: Mac OS Ventura 13.6.1 (22G313)
Obsidian Version: v1.4.16
Wikipedia Search Version: v2.3.1

**Comment by StrangeGirlMurph** [comment]
I am nearly certain you just aren't in edit mode. Please read the documentation on this: https://strangegirlmurph.github.io/obsidian-wikipedia-search/commands/ The command is only available in edit mode.

**Comment by ValiHar** [comment]
Ahhh you're right. :) Then I misunderstood the feature a bit! I thought that I could create a file based on a Wikipedia article, without actually inserting it anywhere. But this should work as well! Thanks for the quick support Murph <3

**Comment by StrangeGirlMurph** [comment]
> I thought that I could create a file based on a Wikipedia article, without actually inserting it anywhere

Yeah I just thought of that too when you replied to the PR. Weird that I haven't thought of that earlier ^^ Well I am home in 30min and will quickly add that feature with a `Create Note` command. Thanks

**Comment by ValiHar** [comment]
That's great, thank you so much 🥳
