### ISSUE TITLE
[FEATURE] Add new file in current directory

### ISSUE THREAD

**Issue by ValiHar** [StrangeGirlMurph/obsidian-wikipedia-search#24]
# Description of the Feature

A note based on a wiki article is currently created in a static path that you specify in the settings. It would be helpful to have a toggle button in the options that, when toggled, allows the creation of wiki notes in the current working directory, i.e. the directory of the currently selected file. When no file is selected the file creation falls back to the default path.

**Comment by StrangeGirlMurph** [comment]
Good idea! Thank you. I will implement it with a special keyword like `current` for the file path field instead of an additional toggle though. The template settings are already cluttered with toggles ^^

**Comment by StrangeGirlMurph** [comment]
Added this feature with the newest release :)

**Comment by ValiHar** [comment]
So fast! ⚡ ⚡ ⚡

**Comment by ValiHar** [comment]
Hi @StrangeGirlMurph, 
somehow this is not working for me 😢 after updating the plugin I can now select "[current folder]" but it keeps generating the files in the previously defined folder. Is there a "buffer" variable that hasn't been updated? 
Thanks and best, 
Val

**Comment by StrangeGirlMurph** [comment]
Hmm weird. Can't reproduce this. Can you send me a copy of you `data.json` file please? You can find it under `[vault]/.obsidian/plugins/wikipedia-search/data.json`

**Comment by ValiHar** [comment]
Sure! Here you go: 
```json
{
  "language": "en",
  "searchLimit": 10,
  "thumbnailWidth": null,
  "defaultNotePath": "[current folder]",
  "templates": [
    {
      "name": "Default",
      "templateString": "{thumbnail}\n[{title}]({url}): \n{intro}",
      "createNote": true,
      "customPath": "KnowledgeBase",
      "useTemplateFile": true,
      "templateFilePath": "Templates/KnowledgeBase Templates/Wiki Note Template.md"
    }
  ],
  "placeCursorInfrontOfInsert": false,
  "autoInsertSingleResponseQueries": false,
  "prioritizeArticleTitle": false,
  "cleanupIntros": true,
  "openArticleInFullscreen": false,
  "openArticlesInBrowser": false,
  "openCreatedNotes": false,
  "overrideFiles": false,
  "showedSurfingMessage": true
}
```

**Comment by StrangeGirlMurph** [comment]
Okay so according to your stored settings everything is fine. Your default note path is set to the current folder but your default template uses the KnowledgeBase folder instead of the default note path. That's why notes will be created in KnowledgeBase instead of the current folder. If you want the default template to use the default note path you have to set delete its value in the settings.

**Comment by ValiHar** [comment]
Ahhh okay now it makes sense. I somehow didn't get that I can specify this in the template again haha. But the case distinction makes sense.
Thanks so much!
