### ISSUE TITLE
[BUG] Not using templates when linking files

### ISSUE THREAD

**Issue by ValiHar** [StrangeGirlMurph/obsidian-wikipedia-search#25]
# Description

When creating a wiki file during the "Wikipedia Search: Link Article" action, a new file is created in the specified default path. However, this file does not use the specified template for the file creation but instead uses a default template. When using the "Wikipedia Search: Create Article Note" action, the template file is used. 

# To Reproduce

1. Create a template file
2. Specify the template file in your settings as the default template
3. Use "Wikipedia Search: Link Article" on a highlighted text in a note 
4. The created note is not using the expected template

# Expected Behavior

The newly created note uses the specified default template.

**Comment by StrangeGirlMurph** [comment]
Oh wow this is embarrassing. I just forgot to implement/copy over the code from the `Create article note` command 🫥
Thank you so much for pointing it out. Fixed it with the latest release.

**Comment by ValiHar** [comment]
Sure thing! The plugin is turning out to be invaluable to me right now! I really love it :)
