### ISSUE TITLE
[FEATURE] Make thumbnailUrl available to be replaced in templates.

### ISSUE THREAD

**Issue by matthieu42morin** [StrangeGirlMurph/obsidian-wikipedia-search#26]
# Description of the Problem

Thumbnail implementation decision is stopping from getting just the image url, sadly this makes it unusable for use in frontmatter for banner plugin for example and other potential use cases.
The **thumbnailUrl variable is only local to the generateInsert function** and is not returned or outputted directly. It's used to replace {thumbnail} in the templateString with the markdown syntax for the image.

I think anyone could have just done exactly what you have written in your docs, i.e. in their template just written: `![{title} Thumbnail](<url-to-thumbnail>)` or `![{title} Thumbnail | <thumbnail-width>](<url-to-thumbnail>)` if the thumbnail width is set.

And replaced <url-to-thumbnail> with the plugins fetched url for the thumbnail...

# Description of the Solution
Now that people probably depend on this in their templates, I propose just giving users the thumbnailUrl

No breaking changes: 
If I understand your code correctly here is what I would add in **./src/utils/generateInsert.ts**: add another replacement operation.
```
if (templateString.includes("{thumbnailUrl}")) {
    const thumbnailUrl: string | null =
        (await getArticleThumbnails([article.title], settings.language))?.[0] ?? null;
    insert = insert.replaceAll("{thumbnailUrl}", thumbnailUrl ?? "");
    if (!thumbnailUrl) new Notice("Could not fetch the articles thumbnail.");
}
```
This code is almost identical to the existing {thumbnail} replacement, but it doesn't wrap the URL in the markdown image syntax. Instead, it just inserts the URL directly.

# Additional

I wrote a parser for only this string, for some reason in templater it just doesn't work with my setup, there's all sorts of bs and I've had it, tried fixing it for a long time. Instead I propose a nonbreaking alternative.

Breaking changes: Using the above and deleting the operation that takes away customizability, potential use cases.

This makes it work with other plugins as well, no idea why this plugin is not more popular.
This is the best and pretty much only working wiki plugin on obsidian so thanks!

**Comment by StrangeGirlMurph** [comment]
Done :) You can update to the newest version. Thanks for the feature request! You should have asked for this earlier if it has been such a hassle... Well now it's here. I hope everything works out great!

Doesn't really matter but to clarify: `{thumbnail}` isn't actually `![{title} Thumbnail](<url-to-thumbnail>)`. I explained it wrong in the docs. It always uses the article title and never the selection like `{titel}` does with the right setting. `![<article-title> Thumbnail](<url-to-thumbnail>)` is what it's actually doing.

Thank you :) I am happy you're enjoying it. Don't be shy to create issues on other things that might come up!

**Comment by matthieu42morin** [comment]
Absolutely wonderful! And you coded it dry unlike me :) Works like a charm, I actually have like 3 things I noticed, bugs and potential enhancements, right back at ya.
