### ISSUE TITLE
[BUG] Default path not displaying all options with forced slash "/" at default for root.

### ISSUE THREAD

**Issue by matthieu42morin** [StrangeGirlMurph/obsidian-wikipedia-search#27]
# Description

Default path not displaying all options with forced slash "/" at default for root.
Path works fine with the Templates, but the default path for all is buggy

# To Reproduce

The only way for me to achieve getting all folders from root listed was by selecting some random folder that did display, which removed the forced slash and then if the folder I wanted was name "Canvases" I would need to rewrite the first letter to 1 and remove the rest, then "1_Fleeting Notes", which was desired, would display.
So I believe this is the culprit here, the Templates don't have forced slashes in their defaults and work fine.

# Expected Behavior

Normally just root folders would display, which does happen without forced /
 
# Additional Info

I believe none needed

# Screenshots 
 
## Forced slash making me see even a subfolder
![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/72525251/ad919c45-445f-4d4f-9a6f-03d95ddffeeb)

## Templates work as expected 

![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/72525251/3a1d8eeb-74b9-43e3-a2fd-32fbe80128b8)

![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/72525251/f0296f84-37ab-4889-b956-707f9b8e9e7d)

# Removing slash workaround as described

![image](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/72525251/5dd57678-4610-4baf-a4df-b817c9c0e5e8)

**Comment by StrangeGirlMurph** [comment]
Oh yeah that's a bug... I am sorry. Thank you for the report! The fix will be available with the next version. I'll wait with the release for your other issues though :)
