### ISSUE TITLE
FR: When executing the command while a word or line is selected, use the selection in the search immediately

### ISSUE THREAD

**Issue by j-maffe** [StrangeGirlMurph/obsidian-wikipedia-search#3]
Hello! You have no idea how much I appreciate this plugin! :D
A really simple idea that would streamline using it would be to allow using selected text as the search automatically. Bonus points if the link is then inserted along with the URL. Thanks a lot!

**Comment by StrangeGirlMurph** [comment]
Happy you're enjoying it :)
Sounds like a great idea! I'll add it right away.

Just to make sure I'll understand you correct though:
Lets say I am writing some text. "Albert Einstein was a nice guy." When I highlight "Albert Einstein" and execute the search command the selected text ("Albert Einstein") would be automatically pasted in as the search term. When selecting the correct article the highlighted text will be a hyperlink to the wiki page. In the end it would be: "\[Albert Einstein](https://en.wikipedia.org/wiki/Albert_Einstein) was a nice guy." Correct? Or should it still follow the format setting and just replace the highlighted text? Or should the highlighted text just replace the `{title}`?

**Comment by StrangeGirlMurph** [comment]
Well I couldn't wait and just implemented it the way I thought it was best. Maybe I'll add some settings for the different variations in the future. Thank you for you feature request! It's really a nice feature.

**Comment by j-maffe** [comment]
Haha I love the enthusiasm! Yes I also agree that it should use the selected text as the title (as if the original text was never changed but a link is added to the selected text).
Thank you so much! :D
