### ISSUE TITLE
[FEATURE] Convert to Markdown and import

### ISSUE THREAD

**Issue by feedhopper** [StrangeGirlMurph/obsidian-wikipedia-search#38]
# Description of the Problem

For a while, I am looking for a tool to easily convert / import wikipedia pages to my vault. I tried lots of things and online converters. The problem is really the conversion of links and references which always fails.

Is there a way to consider an option for an opened page to be directly converted and imported? This would be so great!

# Additional

If there is any way to do so, I would love to have an option to also include the little preview texts that pop up when hovering over the wikipedia links on one of their pages.

**Comment by StrangeGirlMurph** [comment]
Hey :) Thanks for reaching out!
Sadly converting whole Wikipedia articles into markdown isn't feasible for me. What I get from the Wikipedia API is just too different from simple markdown. It's just too much work to convert wikitext to markdown by hand. All the problems other converters have will be the same here.
The little preview text you see is actually just the first few characters of the intro you can already retrieve with the plugin (`{intro}`)
Sorry I can't help more. Maybe check out https://pandoc.org/index.html :)
